config/routes.rb
Transportadora::Application.routes.draw do
  resources :entregas
  resources :clientes
  resources :motoristas

  get '/ufd/:ufd_id/cidades', :to => 'ufds#cidades'
  get '/cidade/:cidade_id/clientes', :to => 'cidades#clientes'
  get '/motoristas/:data/disponiveis', :to => 'motoristas#disponiveis'

  root :to => "entregas#index"

end

app/models/entrega.rb
class Entrega < ActiveRecord::Base
  belongs_to :motorista
  belongs_to :cliente
  belongs_to :cidade
  belongs_to :ufd

  validates_presence_of :data_da_partida, :data_do_retorno, :data_da_entrega

  def em_andamento?
    self.data_da_partida >= Date.today && self.data_do_retorno >= Date.today ? true : false
  end
  
  def estara_em_andamento?(data)
    status = false
    (self.data_da_partida .. (self.data_do_retorno - 1)).each do |data_corrente|
      status = true if data_corrente == data
    end
    status
  end

  def self.estarao_em_andamento(data)
    entregas = Array.new
    Entrega.all.each do |entrega|      
      entregas << entrega if entrega.estara_em_andamento?(data)
    end
    entregas
  end

end

app/controllers/entregas_controller.rb
class EntregasController < ApplicationController
  # GET /entregas
  # GET /entregas.xml

  def index
    @entregas = Entrega.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entregas }
    end
  end

  # GET /entregas/1
  # GET /entregas/1.xml
  def show
    @entrega = Entrega.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entrega }
    end
  end

  # GET /entregas/new
  # GET /entregas/new.xml
  def new
    @entrega = Entrega.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entrega }
    end
  end

  # GET /entregas/1/edit
  def edit
    @entrega = Entrega.find(params[:id])
  end

  # POST /entregas
  # POST /entregas.xml
  def create
    @entrega = Entrega.new(params[:entrega])

    respond_to do |format|
      if @entrega.save
        format.html { redirect_to(@entrega, :notice => 'Entrega was successfully created.') }
        format.xml  { render :xml => @entrega, :status => :created, :location => @entrega }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entrega.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entregas/1
  # PUT /entregas/1.xml
  def update
    @entrega = Entrega.find(params[:id])

    respond_to do |format|
      if @entrega.update_attributes(params[:entrega])
        format.html { redirect_to(@entrega, :notice => 'Entrega was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entrega.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entregas/1
  # DELETE /entregas/1.xml
  def destroy
    @entrega = Entrega.find(params[:id])
    @entrega.destroy

    respond_to do |format|
      format.html { redirect_to(entregas_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/entregas_helper.rb
module EntregasHelper
end

app/views/entregas/_form.html.erb
<% content_for(:head){javascript_include_tag "form"}%>

<%= form_for(@entrega) do |f| %>
  
  <% if @entrega.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrega.errors.count, "error") %> impediram o formulário de ser salvo:</h2>

      <ul>
      <% @entrega.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">  
    <%= f.label "Estado:" %><br />
    <%= f.collection_select :ufd_id, Ufd.all, :id, :nome, {:prompt => "Selecione um estado"} %>
  </div>

  <div class="field">
    <%= f.label "Cidade:" %><br />
    <%= @entrega.new_record? ? (raw "<select id='entrega_cidade_id' name='entrega[cidade_id]' type='text'/><option value=""></option></select>") :(f.collection_select :cidade_id, @entrega.ufd.try(:cidades), :id, :nome, :include_blank => true) %>
  </div>

  <div class="field">
    <%= f.label "Cliente:" %><br />

    <%= 
      if @entrega.new_record? || @entrega.cliente.nil?
        raw "<select id='entrega_cliente_id' name='entrega[cliente_id]' type='text'/><option value=""></option></select>"
      else
        raw "<select id='entrega_cliente_id' name='entrega[cliente_id]' type='text'/><option value=#{@entrega.cliente_id}>#{@entrega.cliente.nome_fantasia}</option></select>" 
      end
    %>
  </div>
  
  <div class="field">
    <%= f.label "Data da partida:" %><br />
    <%= f.text_field :data_da_partida %>
  </div>

  <div class="field">
    <%= f.label "Data da entrega:" %><br />
    <%= f.text_field :data_da_entrega %>
  </div>

  <div class="field">
    <%= f.label "Data do retorno:" %><br />
    <%= f.text_field :data_do_retorno %>
  </div>

  <div class="field">
    <%= f.label "Motorista:" %><br />
    <%= 
      if @entrega.new_record?
        raw "<select id='entrega_motorista_id' name='entrega[motorista_id]' type='text'/></select>"
      else
        raw "<select id='entrega_motorista_id' name='entrega[motorista_id]' type='text'/><option value=#{@entrega.motorista_id}>#{@entrega.motorista.nome}</option></select>" 
      end
    %>
  </div>
  
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/entregas/edit.html.erb
<h1>Editar entrega</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @entrega %> |
<%= link_to 'Voltar', entregas_path %>

app/views/entregas/index.html.erb
<h1>Lista de Entregas</h1>

<%= link_to 'Nova Entrega', new_entrega_path %><br />

<table>
  <tr>
    <th width="50" align="left">Id</th>
    <th width="200" align="left">Cliente</th>
    <th width="200" align="left">Motorista</th>
    <th width="110" align="left">Estado</th>
    <th width="110" align="left">Cidade</th>
    <th width="110" align="left">Em andamento?</th>
    <th width="120" align="center">Data da partida</th>
    <th width="120" align="center">Data da entrega</th>
    <th width="120" align="center">Date do retorno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entregas.each do |entrega| %>
  <tr>
    <td><%= entrega.id %></td>
    <td><%= entrega.cliente.nil? ? "" : entrega.cliente.nome_fantasia %></td>
    <td><%= entrega.motorista.nome %></td>
    <td><%= entrega.ufd.nome %></td>
    <td><%= entrega.cidade.nil? ? "" : entrega.cidade.nome %></td>
    <td><%= entrega.em_andamento? ? "Sim" : "Não" %></td>
    <td><%= entrega.data_da_partida.to_s_br %></td>
    <td><%= entrega.data_da_entrega.to_s_br %></td>
    <td><%= entrega.data_do_retorno.to_s_br %></td>
    <td><%= link_to 'Exibir', entrega %></td>
    <td><%= link_to 'Editar', edit_entrega_path(entrega) %></td>
    <td><%= link_to 'Apagar', entrega, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/entregas/new.html.erb
<h1>Nova entrega</h1>

<%= render 'form' %>

<%= link_to 'Voltar', entregas_path %>

app/views/entregas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @entrega.cliente_id %>
</p>

<p>
  <b>Motorista:</b>
  <%= @entrega.motorista_id %>
</p>

<p>
  <b>Cidade:</b>
  <%= @entrega.cidade_id %>
</p>

<p>
  <b>Data da partida:</b>
  <%= @entrega.data_da_partida %>
</p>

<p>
  <b>Data da entrega:</b>
  <%= @entrega.data_da_entrega %>
</p>

<p>
  <b>Date do retorno:</b>
  <%= @entrega.data_do_retorno %>
</p>


<%= link_to 'Editar', edit_entrega_path(@entrega) %> |
<%= link_to 'Voltar', entregas_path %>