config/routes.rb
Transportadora::Application.routes.draw do
  resources :entregas
  resources :clientes
  resources :motoristas

  get '/ufd/:ufd_id/cidades', :to => 'ufds#cidades'
  get '/cidade/:cidade_id/clientes', :to => 'cidades#clientes'
  get '/motoristas/:data/disponiveis', :to => 'motoristas#disponiveis'

  root :to => "entregas#index"

end

app/models/motorista.rb
class Motorista < ActiveRecord::Base
  has_many :entregas


  def disponivel?
    status = true;
    self.entregas.each do |entrega|
      status = false if entrega.em_andamento?
    end
    status
  end
  
  def self.disponiveis(data)
    motoristas = Motorista.all
    Entrega.estarao_em_andamento(data).each do |entrega|
      motoristas.delete(entrega.motorista)
    end
    motoristas
  end

end

app/controllers/motoristas_controller.rb
class MotoristasController < ApplicationController
  # GET /motoristas
  # GET /motoristas.xml

  def disponiveis
    @motoristas = Motorista.disponiveis(params[:data].to_date)
    respond_to do |format|
      format.json {render :json => @motoristas}
    end
  end

  def index
    @motoristas = Motorista.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @motoristas }
    end
  end

  # GET /motoristas/1
  # GET /motoristas/1.xml
  def show
    @motorista = Motorista.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @motorista }
    end
  end

  # GET /motoristas/new
  # GET /motoristas/new.xml
  def new
    @motorista = Motorista.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @motorista }
    end
  end

  # GET /motoristas/1/edit
  def edit
    @motorista = Motorista.find(params[:id])
  end

  # POST /motoristas
  # POST /motoristas.xml
  def create
    @motorista = Motorista.new(params[:motorista])

    respond_to do |format|
      if @motorista.save
        format.html { redirect_to(@motorista, :notice => 'Motorista was successfully created.') }
        format.xml  { render :xml => @motorista, :status => :created, :location => @motorista }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @motorista.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /motoristas/1
  # PUT /motoristas/1.xml
  def update
    @motorista = Motorista.find(params[:id])

    respond_to do |format|
      if @motorista.update_attributes(params[:motorista])
        format.html { redirect_to(@motorista, :notice => 'Motorista was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @motorista.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /motoristas/1
  # DELETE /motoristas/1.xml
  def destroy
    @motorista = Motorista.find(params[:id])
    @motorista.destroy

    respond_to do |format|
      format.html { redirect_to(motoristas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/motoristas_helper.rb
module MotoristasHelper
end

app/views/motoristas/_form.html.erb
<% content_for(:head){javascript_include_tag "form"}%>
<%= form_for(@motorista) do |f| %>
  <% if @motorista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motorista.errors.count, "error") %> impediram o formulário de ser salvo:</h2>

      <ul>
      <% @motorista.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Nome:' %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label "Telefone:" %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/motoristas/edit.html.erb
<h1>Editar motorista</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @motorista %> |
<%= link_to 'Voltar', motoristas_path %>

app/views/motoristas/index.html.erb
<h1>Lista de Motoristas</h1>

<%= link_to 'Novo Motorista', new_motorista_path %><br />

<table>
  <tr>
    <th width="300" align="left">Nome</th>
    <th width="200" align="left">Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @motoristas.each do |motorista| %>
  <tr>
    <td><%= motorista.nome %></td>
    <td><%= motorista.telefone %></td>
    <td><%= link_to 'Exibir', motorista %></td>
    <td><%= link_to 'Editar', edit_motorista_path(motorista) %></td>
    <td><%= link_to 'Apagar', motorista, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/motoristas/new.html.erb
<h1>Novo motorista</h1>

<%= render 'form' %>

<%= link_to 'Voltar', motoristas_path %>

app/views/motoristas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @motorista.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @motorista.telefone %>
</p>


<%= link_to 'Editar', edit_motorista_path(@motorista) %> |
<%= link_to 'Voltar', motoristas_path %>